In [1]:
import torch

In [2]:
batch_size=32
feature_size=128

x = torch.rand(batch_size, feature_size)

In [3]:
print(x)

tensor([[0.3427, 0.8660, 0.0881,  ..., 0.8776, 0.0371, 0.6436],
        [0.1425, 0.0932, 0.8791,  ..., 0.5070, 0.3899, 0.3656],
        [0.9490, 0.5763, 0.2677,  ..., 0.2575, 0.3487, 0.2065],
        ...,
        [0.3497, 0.8448, 0.0293,  ..., 0.1837, 0.7641, 0.7176],
        [0.8421, 0.9799, 0.8537,  ..., 0.1733, 0.2702, 0.6323],
        [0.0278, 0.9603, 0.2345,  ..., 0.2703, 0.2956, 0.4255]])


In [5]:
in_features = 128
out_features = 64
layer_1 = torch.nn.Linear(
    in_features=in_features,
    out_features=out_features,
    bias=True
)

In [7]:
layer_1.weight.shape

torch.Size([64, 128])

In [8]:
x = torch.rand(8, 128)

In [9]:
output_1 = layer_1(x)

In [12]:
output_2 = x @ layer_1.weight.T + layer_1.bias

In [13]:
print(output_1[0, 1])

tensor(0.4037, grad_fn=<SelectBackward0>)


In [14]:
print(output_2[0, 1])

tensor(0.4037, grad_fn=<SelectBackward0>)


In [20]:
# Sigmoid
x = torch.rand(8, 128)

act_fn = torch.nn.Sigmoid()

out = act_fn(x)

In [21]:
out.shape

torch.Size([8, 128])

In [22]:
# Tanh
x = torch.rand(8, 128)

act_fn = torch.nn.Tanh()

out = act_fn(x)

In [23]:
out.shape

torch.Size([8, 128])

In [24]:
#ReLU
x = torch.rand(8, 128)

act_fn = torch.nn.ReLU()

out = act_fn(x)
out.shape

torch.Size([8, 128])

In [45]:
#Softmax
logits = torch.rand(1, 20)

softmax = torch.nn.Softmax(dim=1)

preb_probab = softmax(logits)
preb_probab.shape

torch.Size([1, 20])

In [46]:
print("Sum of Logits =",torch.sum(logits, dim=1).item())
print("Sum of softmaxed Logits =",torch.sum(preb_probab, dim=1).item())

Sum of Logits = 9.282567024230957
Sum of softmaxed Logits = 0.9999999403953552


In [47]:
preb_probab

tensor([[0.0628, 0.0785, 0.0346, 0.0465, 0.0788, 0.0343, 0.0307, 0.0301, 0.0535,
         0.0458, 0.0784, 0.0366, 0.0450, 0.0314, 0.0788, 0.0316, 0.0594, 0.0629,
         0.0464, 0.0337]])

In [48]:
#Fully Connected Neural Network
#Feature Vector 128 -> 64로 변환하는 Layer
#FC Layer + Tanh으로 구성

in_features= 128
out_features= 64

layer_1 = torch.nn.Linear(
    in_features=in_features,
    out_features=out_features,
    bias=True
)

act_fn_1 = torch.nn.Tanh()

In [49]:
#Second Layer
# 64 -> 16으로 변환하는 Layer
#FC Layer + Tanh으로 구성

in_features= 64
out_features= 16

layer_2 = torch.nn.Linear(
    in_features=in_features,
    out_features=out_features,
    bias=True
)

act_fn_2 = torch.nn.Tanh()

In [50]:
#Third Layer
# 16 -> 1으로 변환하는 Layer
#FC Layer + Sigmoid로 구성

in_features= 16
out_features= 1

layer_3 = torch.nn.Linear(
    in_features=in_features,
    out_features=out_features,
    bias=True
)

act_fn_3 = torch.nn.Sigmoid()

In [51]:
out_1 = act_fn_1(layer_1(x))

In [52]:
out_2 = act_fn_2(layer_2(out_1))

In [53]:
out_3 = act_fn_3(layer_3(out_2))

In [54]:
out_3.shape

torch.Size([8, 1])

In [55]:
print(out_3)

tensor([[0.4946],
        [0.4925],
        [0.4887],
        [0.4960],
        [0.4797],
        [0.5323],
        [0.4885],
        [0.4302]], grad_fn=<SigmoidBackward0>)


In [56]:
model = torch.nn.Sequential(
    torch.nn.Linear(
        in_features=128,
        out_features=64,
        bias=True
    ),
    torch.nn.Tanh(),
    torch.nn.Linear(
        in_features=64,
        out_features=16,
        bias=True
    ),
    torch.nn.Tanh(),
    torch.nn.Linear(
        in_features=16,
        out_features=1,
        bias=True
    ),
    torch.nn.Sigmoid()
)

In [57]:
x = torch.rand(32, 128)
out = model(x)

In [58]:
out.shape

torch.Size([32, 1])

In [59]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(
                in_features=128,
                out_features=64,
                bias=True
            ),
            torch.nn.Tanh(),
            torch.nn.Linear(
                in_features=64,
                out_features=16,
                bias=True
            ),
            torch.nn.Tanh(),
            torch.nn.Linear(
                in_features=16,
                out_features=1,
                bias=True
            ),
            torch.nn.Sigmoid()
        )
    def forward(self, x):
        return self.layers(x)

In [60]:
model = Model()

In [61]:
x = torch.rand(32, 128)
out = model(x)

In [62]:
out.shape

torch.Size([32, 1])

In [63]:
model

Model(
  (layers): Sequential(
    (0): Linear(in_features=128, out_features=64, bias=True)
    (1): Tanh()
    (2): Linear(in_features=64, out_features=16, bias=True)
    (3): Tanh()
    (4): Linear(in_features=16, out_features=1, bias=True)
    (5): Sigmoid()
  )
)

In [64]:
!pip install torchsummary

In [65]:
from torchsummary import summary

In [66]:
summary(model, (128,))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                   [-1, 64]           8,256
              Tanh-2                   [-1, 64]               0
            Linear-3                   [-1, 16]           1,040
              Tanh-4                   [-1, 16]               0
            Linear-5                    [-1, 1]              17
           Sigmoid-6                    [-1, 1]               0
Total params: 9,313
Trainable params: 9,313
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.04
Estimated Total Size (MB): 0.04
----------------------------------------------------------------
