In [1]:
import numpy as np
import torch

In [2]:
data = [[1,2], [3,4]]

In [3]:
x_data = torch.tensor(data)

In [4]:
x_data.dtype

torch.int64

In [6]:
shape = (2,3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor:\n {rand_tensor} \n")
print(f"Ones Tensor:\n {ones_tensor} \n")
print(f"Zeros Tensor:\n {zeros_tensor} \n")

Random Tensor:
 tensor([[0.6509, 0.6056, 0.5627],
        [0.8999, 0.6786, 0.3864]]) 

Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [7]:
data = [[1,2], [3,4]]

np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [8]:
x_np

tensor([[1, 2],
        [3, 4]])

In [9]:
x_np.dtype

torch.int64

In [10]:
x_data = torch.tensor(data, dtype= torch.float32)

In [11]:
x_data.dtype

torch.float32

In [13]:
 torch.cuda.is_available()

False

In [14]:
x_data = x_data.to("cuda")

AssertionError: Torch not compiled with CUDA enabled

In [15]:
x_data = x_data.to("cpu")

In [16]:
x_data.device

device(type='cpu')

In [17]:
tensor = torch.ones(4,4)

In [18]:
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [19]:
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [20]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

In [21]:
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [22]:
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [23]:
 z1 = tensor * tensor.T
z2 = tensor.mul(tensor.T)

In [24]:
z1

tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [25]:
z2

tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [ ]:
tensor.add_(5)